### ISSUE TITLE
The model structure is inconsistent with the code description

### ISSUE THREAD

**Issue by AliasChenYi** [tiny-smart/dysample#10]
The model structure is inconsistent with the code descriptiom.

**Comment by AliasChenYi** [comment]
![image](https://github.com/tiny-smart/dysample/assets/91005746/fc4434fe-6d4a-4f32-940b-0259d43d2d8a)
![image](https://github.com/tiny-smart/dysample/assets/91005746/9e487e43-6ef0-488d-8d83-3e3d630251ab)

**Comment by AliasChenYi** [comment]
The model structure is pixel shuffle and then g, but the code implementation is to add g first and then pixel shuffle

**Comment by poppuppy** [comment]
Hi. They are just equivalent.
