### ISSUE TITLE
Can feature scale upsampling be singular before and after, such as x1=(1, 64, 80, 45) x2=(1, 64, 40, 23)

### ISSUE THREAD

**Issue by Prown666** [tiny-smart/dysample#15]
Can feature scale upsampling be singular before and after, such as x1=(1, 64, 80, 45) x2=(1, 64, 40, 23)

**Comment by poppuppy** [comment]
Conceptually it can, but, the current implementation can not. To obtain such a downsampler as you said, you can use x1 to generate sampling points of size (40, 23) and then resample x1 to x2.
