### ISSUE TITLE
Why do I replace the deconvolution of the decoder with Dysample(lp) during training? The GPU memory overhead is even greater，From the original 17GB to 22GB

### ISSUE THREAD

**Issue by malatang20001210** [tiny-smart/dysample#17]

**Comment by poppuppy** [comment]
In general the memory of DySample is smaller. Can you specify your operation a little?

**Comment by malatang20001210** [comment]
![10ab677aad795798744042a5c0cec45](https://github.com/user-attachments/assets/776a3c7d-fb74-4898-a889-134dd5d037c1)
![c61c0d359e3acd8684e823e1521ed29](https://github.com/user-attachments/assets/bbc199aa-ab07-4896-8b04-a67a71dad976)
Taking Dlinknet as an example in the figure, the size of the GPU memory is shown at the bottom. I don't know if this is the right operation, but if the final deconvolution is directly replaced, the GPU memory will be greatly improved, so where should I add this module?

**Comment by poppuppy** [comment]
I think maybe filters[0] is much greater than 32, so there is much increased memory in self.finalconv2.

**Comment by malatang20001210** [comment]
But its 64 ,is it relatively big?

**Comment by malatang20001210** [comment]
![image](https://github.com/user-attachments/assets/3872f07c-2d9b-4081-ab67-8faff5691504)

**Comment by poppuppy** [comment]
64 is not big. But the image size is 1024?

**Comment by malatang20001210** [comment]
yes

**Comment by malatang20001210** [comment]
> I think maybe filters[0] is much greater than 32, so there is much increased memory in self.finalconv2.

oh maybe your thought is right

**Comment by poppuppy** [comment]
1024 is very large resolution. You can try to use a 1x1 conv to first reduce the channel number from 64 to 32, and then apply dysample at the 32 level.

**Comment by malatang20001210** [comment]
Thank you very much for your prompt response and guidance！！

**Comment by poppuppy** [comment]
Happy to help
