### ISSUE TITLE
请问下作者，您的pytorch版本中meshgrid函数indexing的默认值是哪个

### ISSUE THREAD

**Issue by NeKoooo233** [tiny-smart/dysample#3]
我这里报出了一个UserWarning，让我显式确定meshgrid函数indexing的值
indexing='ij'或者indexing='xy‘
希望您能确认一下
我将非常感谢

**Comment by teleppo** [comment]
你好，在我使用的python(3.8.8)和PyTorch(1.9.0)版本下没有这个Warning。indexing默认值应为'ij'。可能你使用了更高版本的PyTorch，请参考https://pytorch.org/docs/stable/generated/torch.meshgrid.html?highlight=meshgrid的WARNING。

**Comment by NeKoooo233** [comment]
> 你好，在我使用的python(3.8.8)和PyTorch(1.9.0)版本下没有这个Warning。indexing默认值应为'ij'。可能你使用了更高版本的PyTorch，请参考[https://pytorch.org/docs/stable/generated/torch.meshgrid.html?highlight=meshgrid的WARNING。](https://pytorch.org/docs/stable/generated/torch.meshgrid.html?highlight=meshgrid%E7%9A%84WARNING%E3%80%82)

非常感谢
