### ISSUE TITLE
dysample channel 

### ISSUE THREAD

**Issue by nzomi** [tiny-smart/dysample#7]
Hi, I noticed that the dysample can be used for same channel transformation. 
e.g., from (1, 64, 256, 256) → (1, 64, 256*scale, 256*scale)

If I want to change the output channel while using dysample,  I think I can only follow these steps:
e.g., from channel 64 to channel 32
1. Apply dysample to change spatial resolution: (1, 64, 256, 256) → (1, 64, 256*scale, 256*scale)
2. Add a convolution layer to adjust the channel: (1, 64, 256*scale, 256*scale) → (1, 32, 256*scale, 256*scale)
or do the channel reduction firstly then applying dysample.

Is there any method to adjust the ouput channel without using more convolution layers?

**Comment by poppuppy** [comment]
Hi. There is no operation for changing channel numbers in DySample. I recommend to first use DySample and then use a linear/1x1conv layer to reduce the channel number.
